name: jmessage_flutter
description: JIGUANG officially supported JMessage Flutter plugin (Android & iOS). 极光推送官方支持的 Flutter 插件（Android & iOS）(https://www.jiguang.cn).
version: 0.6.3
homepage: https://www.jiguang.cn

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: com.jiguang.jmessageflutter
    pluginClass: JmessageFlutterPlugin
